# https://github.com/actions/starter-workflows/tree/main/ci
# https://github.com/marketplace?category=code-quality&type=actions
name: product-catalogue-ci
on:
  pull_request:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup-go-1.22
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.6'
    
    - name: build
      run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog .

    - name: test
      run: |
            cd src/product-catalog
            go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install-docker
      uses: docker/setup-buildx-action@v3

    - name: docker-login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name : build-and-push
      uses: docker/build-push-action@v6
      with:
        context: src/product-catalog
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-catalogue-service:${{github.run_id}}


  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GEETHUB_TOKEN }}
    
    - name: update-tag-in-k8s-manifest
      run: |
            sudo apt install wget
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod a+x /usr/local/bin/yq
            export PATH=/usr/local/bin:$PATH
            yq  '.spec.template.spec.containers[0].image' kubernetes/productcatalog/deploy.yaml
            yq e  '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/product-catalogue-service:${{ github.run_id }}"' -i kubernetes/productcatalog/deploy.yaml

    - name: commit-push-message
      run : |
          git config user.name "${{ vars.GEETHUB_USERNAME }}"
          git config user.email "${{ vars.GEETHUB_EMAIL }}"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI] update product catalogue service docker image tag to ${{ github.run_id }}"
          git push origin HEAD:main -f

    

    


  


    


    

    
